### PR TITLE
Added section convert environment maps to cubemaps

### PR DESCRIPTION
**Pull request by yaustar**
Fixes https://github.com/playcanvas/developer.playcanvas.com/issues/284

Updated Mon 1 Aug 2022:

image

### CODE REVIEW

**Comment by yaustar** [comment]
Will have to update doc due to this PR https://github.com/playcanvas/texture-tool/pull/18

**Comment by yaustar** [comment]
Updated instructions to match Donovan's latest PR

**Comment by willeastcott** [comment]
Wait, shouldn't people be exporting the faces to HDR and not PNG? HDR is RGBE and PNG is RGBM, right?

Also, for that 2048x1024 equirect, suggesting 2048 as a cube face size is way too excessive. 512 is much more reasonable.

**Comment by slimbuck** [comment]
Yep HDR is RGBE only while PNG can store any of the encodings (RGBE, RGBM, RGBP).

For use in the PC editor, exported textures should either be RGBM PNG or HDR.

**Comment by slimbuck** [comment]
> Also, for that 2048x1024 equirect, suggesting 2048 as a cube face size is way too excessive. 512 is much more reasonable.

Agree!

**Comment by yaustar** [comment]
> suggesting 2048 as a cube face size is way too excessive

Oh, that was to point at the setting area and that was just the default setting in the tool. Wasn't really a suggestion and more, 'enter you size here' pointer.

Happy to change the image and the copy to suggest 512 instead.

Just to be clear, should be telling users to use HDR that can be imported into PlayCanvas?

**Comment by willeastcott** [comment]
I assume the following are valid:

* Encoding: RGBE + HDR
* Encoding: RGBM + PNG

...but @slimbuck to confirm.

**Comment by yaustar** [comment]
Going on a tangent, if that's the case why have the encoding as a separate option?

**Comment by yaustar** [comment]
Updated based on feedback from Donovan and Will

**Review by slimbuck — APPROVED** [review]

**Pull request merged**
