### PR TITLE
Added social links to site header

### PR DESCRIPTION
**Pull request by yaustar**
Updated Tue 23 Nov 2021

Header
image

Footer
image

### CODE REVIEW

**Comment by yaustar** [comment]
Still needs work. I forgot I need to do the hover effect

**Comment by yaustar** [comment]
Done now :)

**Comment by willeastcott** [comment]
They're a bit, um, in your face. Could they be better located in the top nav bar to the right of the API reference link?

**Comment by yaustar** [comment]
> They're a bit, um, in your face. Could they be better located in the top nav bar to the right of the API reference link?

Maybe. I could reduce the spacing between the text links and reduce the size?

**Comment by yaustar** [comment]
Would this be better @willeastcott?
image

I can also try an inline variant too

**Comment by willeastcott** [comment]
I think the fact they're a bit smaller here is better, yeah, but it's the fact they're not in the header bar that's bothering me a lot more.

**Comment by yaustar** [comment]
image

**Comment by yaustar** [comment]
Or go a little bigger:
image

**Comment by yaustar** [comment]
Alternatively, we could list them here which may be better?

**Comment by yaustar** [comment]
Decided to go simple in the end:

Header
image

Footer
image

**Review by willeastcott — APPROVED** [review]
Approving (assuming you've checked it works OK on mobile). 😄

**Comment by yaustar** [comment]
Works 'ok' on mobile in the sense it does the same thing as before 😅

**Pull request merged**
