### PR TITLE
Updated tween code sample for onUpdate

### PR DESCRIPTION
**Pull request by yaustar**
Fixes https://github.com/playcanvas/developer.playcanvas.com/issues/528

Updated the code sample for getting a callback on every update in the tween

image

Forked project and uses the render component https://playcanvas.com/project/1190774/overview/using-the-tween-library

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/developer.playcanvas.com/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by willeastcott — APPROVED** [review]

**Comment by yaustar** [comment]
I still have access to the actual PlayCanvas tween project if you would like me to directly update that @willeastcott ?

**Comment by willeastcott** [comment]
Want me to simply give you access to the original project? 😄 

Thanks for this!!

**Comment by willeastcott** [comment]
Oh wait! You're already admin...

**Comment by willeastcott** [comment]
Please do go ahead and update it @yaustar. You rock! 🙏

**Comment by yaustar** [comment]
Updated the PlayCanvas owned tween project 👍 

For some reason I already did the render component update a while back but not merged it 😅 All fixed now 😄

**Pull request merged**
