### PR TITLE
Code Editor Monaco upgrade

### PR DESCRIPTION
**Pull request by yaustar**
image

### CODE REVIEW

**Comment by willeastcott** [comment]
Can you crop the Preferences screenshot?

**Comment by yaustar** [comment]
> Can you crop the Preferences screenshot?

Done! :)

**Review by willeastcott — APPROVED** [review]

**Review by yak32 — APPROVED** [review]
how did you create such a huge screenshot?

**Comment by willeastcott** [comment]
@yak32 https://support.mozilla.org/en-US/kb/take-screenshots-firefox

**Pull request merged**
