### PR TITLE
Updated animated textures tutorial code to work with engine 1.46.0

### PR DESCRIPTION
**Pull request by yaustar**
(Side note: Done this via https://github.dev/ and it works well for quick changes/updates!)

Tutorial project has been updated: https://playcanvas.com/editor/scene/440164

### CODE REVIEW

**Comment by willeastcott** [comment]
Is now a good time to retire this tutorial. Or completely rewrite it? To do a spinning coin, a developer should be using an animated sprite! Animated sprites were not implemented when this tutorial was written originally.

I'd rather this just stuck to the public API of using tiling, offset and rotation to manipulate a texture.

**Comment by yaustar** [comment]
Hmm, we don't have anything API wise to change tiling/offset on the mesh instance basis though?

Maybe we could retire the written tutorial and keep it as a project sample?

**Comment by willeastcott** [comment]
> Hmm, we don't have anything API wise to change tiling/offset on the mesh instance basis though?
Well, per-mesh-instance state is set with the (IMHO) nasty `setParameter` function. Why is it nasty? Because it takes uniform names as a parameter, but we don't document these uniform names anywhere, or document the types and format of the data set on each uniform. And if people do use this API, their projects are more liable to breaking when we modify shader chunks (as we see in this case). IMHO, it shouldn't be something we draw attention too.

> Maybe we could retire the written tutorial and keep it as a project sample?
Well, like I say, I think a practical demonstration of how to tile, scale and rotate textures is great. I just think doing this per-mesh instance is a bit niche. In this case, it's actually bad information, because anyone who sees this tutorial might use this for their animated sprites.....instead of animated sprites!

Also, you'd have to want to do this on a *lot* of mesh instances before it's worth it performance wise.

**Comment by yaustar** [comment]
Okay, in which case we can remove the animated 'sprite' texture part (maybe keep a fork for reference if someone needs it) and when we get texture rotation in, expand the tutorial at a later stage

**Comment by willeastcott** [comment]
Sounds good 👍

**Comment by yaustar** [comment]
I've updated the tutorial and removed the sprite animation part:
image

The project changes are now in the render update branch so we can release all these changes at once

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
Good to see the `setParameter` stuff gone. Approving (although kinda still wish the tutorial project itself was better - it's not showing off the new texture rotation part of the API).

**Pull request merged**
