### PR TITLE
Updated & fixed real-time-multiplayer tutorial

### PR DESCRIPTION
**Pull request by OmarShehata**
This PR updates the tutorial to follow the fixes I made for this issue: https://github.com/playcanvas/developer.playcanvas.com/issues/51

### Changes to the Project

* Server is now hosted on Glitch where it's open and accessible (and can be forked) 
  * This also fixes the https issue 
* Server can now handle disconnects  

### Changes to the Tutorial

* More readable editor screenshots
* Instructions on how to use Glitch instead of setting up a local server
* Each step asks you to add a new piece of code, making it easier to follow, instead of having to figure out which code section to copy and accidentally duplicating functions.
* Added a link to my [multiplayer tutorial](https://code.tutsplus.com/tutorials/create-a-multiplayer-pirate-shooter-game-in-your-browser--cms-23311?_ga=2.87271002.33673392.1518211151-2068440627.1473999710) at the end .
  * That tutorial goes more in depth about networking and Socket.io in general, while this tutorial focuses specifically on how to set things up within PlayCanvas, so I think they complement each other well .
  * Of course I'm biased and we can remove it if you don't think it fits.

### CODE REVIEW

**Comment by willeastcott** [comment]
Yay! This is fantastic. Thanks, @OmarShehata! 👍

**Comment by willeastcott** [comment]
This is now [live](https://developer.playcanvas.com/en/tutorials/real-time-multiplayer/).

**Comment by willeastcott** [comment]
I'm seeing the following:

Failed to load https://playcanvas-multiplayer.glitch.me/socket.io/?EIO=3&transport=polling&t=M6BChUR: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://playcanv.as' is therefore not allowed access. The response had HTTP status code 503.

**Comment by OmarShehata** [comment]
I'm having trouble recreating that. It's working on both Chrome and Firefox for me. There are some [suggested solutions](https://github.com/socketio/socket.io/issues/2294) but it's hard to verify if it works if I can't recreate it.

I can try testing on more environments.

**Comment by willeastcott** [comment]
Actually, it works at home but not at my office. Could be related to my network.

**Pull request merged**
